@startuml
'https://plantuml.com/class-diagram
namespace Player{
    PlayerComponentFactory <.. PlayerContactDetector
    ScoreCalucurator .> CoinCollector
    PlayerComponentFactory -Result.ResultView
    
    class CoinCollector{
        Dictionary<CoinType,int> collectCoinNumber              
    }
    class PlayerMover{
        Move()
    }
    class PlayerComponentFactory{
    }
    class PlayerContactDetector{}
    class ScoreCalucurator{
    }
}

Items.ITouchble <. Player.PlayerContactDetector
Player.PlayerContactDetector <-- Player.CoinCollector

namespace Items{
    Items.ITouchble <|.. Coin
    Items.ITouchble <|.. Enadori
    CoinGenerator -- Coin
    Coin -- CoinType
    interface ITouchble{
        touch()
    }
    
    class Coin{
        CoinType type
        touch()   
    }
   
    class CoinGenerator{
        void Generate()
        void GenerateLoop()
    }
   
    class Enadori{
    }
    enum CoinType{
    }
}
namespace InGameUI{
    class view{
        # CoinCollecter CoinCollecter
        
    }
}

'リザルト結果
namespace Result{
    class ResultView{   
    }

}

namespace StartView{
    
}
namespace GameLoops{
    GameLoop --- Items.CoinGenerator
    GameLoop --- Result.ResultView
    class GameLoop{}
}

@enduml